apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-config" 
  namespace: {{ .Values.namespace }}
data:
  APP_PORT: "{{ .Values.container.port }}"
  NEW_SERVICE: "{{ .Values.configMap.newAService }}"