apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.name }}-app"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}-app"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}-app"
    spec:
      containers:
        - name: "{{ .Values.name }}-node"
          image: "{{ .Values.container.image }}:build-{{ .Values.container.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            requests:
              cpu: "{{ .Values.resources.request.cpu }}"
              memory: "{{ .Values.resources.request.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          envFrom:
            - configMapRef:
                name: "{{ .Values.name }}-config"
            - secretRef:
                name: "{{ .Values.name }}-secret"
          startupProbe:
            httpGet:
              path: /startup
              port: {{ .Values.container.port }}
            failureThreshold: {{ .Values.container.failureThreshold }}
            periodSeconds: {{ .Values.container.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.container.port }}
            failureThreshold: {{ .Values.container.failureThreshold }}
            initialDelaySeconds: {{ .Values.container.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.container.port }}
            failureThreshold: {{ .Values.container.failureThreshold }}
            initialDelaySeconds: {{ .Values.container.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.periodSeconds }}