apiVersion: v1
kind: Service
metadata:
  name:  "{{ .Values.name }}-service"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: "{{ .Values.name }}-app"
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}     
      targetPort: {{ .Values.service.targetPort }}       
  type: {{ .Values.service.type }}
  